#! /bin/csh -f
#  grc
#
set pen = 1

#set axis =
#set axis = "-T 3"
set axis = "-T 1"

# set mk =
#set mk = "-c o"
set mk = "-C o"

#set csiz = 
set csiz = "-w 6 -W 6"

set min = 
#set min = "-m -.1"

set max = 
#set max = "-M 1.2"

#set plot = "vid  -m 1.5  -y 6700"

if ($#argv == 1) then
   graph -p $pen $csiz $axis $min $max $mk -f $1 

else if ($#argv == 2) then
   graph -p $pen $csiz $axis $min $max $mk -f $1 $mk -f $2 

else if ($#argv == 3) then
   graph -p $pen $csiz $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 

else if ($#argv == 4) then
   graph -p $pen $csiz $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 $mk -f $4

else if ($#argv == 5) then
   graph -p $pen $csiz $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 $mk -f $4 $mk -f $5

else if ($#argv == 6) then
  graph -p $pen $csiz $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 $mk -f $4 $mk -f $5 $mk -f $6

else if ($#argv == 7) then
  graph -p $pen $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 $mk -f $4 $mk -f $5 $mk -f $6 $mk -f $7

else if ($#argv == 8) then
 graph -p $pen $axis $min $max $mk -f $1 $mk -f $2 $mk -f $3 $mk -f $4 $mk -f $5 $mk -f $6 $mk -f $7 $mk -f $8

endif

