#! /bin/csh -f
#
set pen = 1

#set axis =
#set axis = "-T 3"
set axis = "-T 1"

#set csiz = 
set csiz = "-w 6 -W 6"

#set min = 
set min = "-m -.1"

#set max = 
set max = "-M 1.3"

#set plot = "vid  -m 1.5  -y 6700"

if ($#argv == 1) then
   graph -p $pen $csiz $axis $min $max -f $1 

else if ($#argv == 2) then
   graph -p $pen $csiz $axis $min $max -f $1 -f $2 

else if ($#argv == 3) then
   graph -p $pen $csiz $axis $min $max -f $1 -f $2 -f $3 

else if ($#argv == 4) then
   graph -p $pen $csiz $axis $min $max -f $1 -f $2 -f $3 -f $4

else if ($#argv == 5) then
   graph -p $pen $csiz $axis $min $max -f $1 -f $2 -f $3 -f $4 -f $5

else if ($#argv == 6) then
  graph -p $pen $csiz $axis $min $max -f $1 -f $2 -f $3 -f $4 -f $5 -f $6

else if ($#argv == 7) then
  graph -p $pen $axis $min $max -f $1 -f $2 -f $3 -f $4 -f $5 -f $6 -f $7

else if ($#argv == 8) then
 graph -p $pen $axis $min $max -f $1 -f $2 -f $3 -f $4 -f $5 -f $6 -f $7 -f $8

endif

