#! /bin/csh -f
#  grc
#
set pen = 2

#set axis =
#set axis = "-T 3"
set axis = "-T 1"

# set mk =
set mk1 = 
set mk2 = 
set mk3 = 
set mk4 = 
set mk5 = 
set mk6 = 
set mk7 = 
set mk8 = 

#set csiz = 
set csiz = "-w 6 -W 6 -v 6"

set min =
#set min = "-m -.1"

#set grid = "-g 0"

set max =
set max = "-M 0.10"
#set max = "-M 1.2"

#set plot = "vid  -m 1.5  -y 6700"

if ($#argv == 1) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 

else if ($#argv == 2) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 

else if ($#argv == 3) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 

else if ($#argv == 4) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4

else if ($#argv == 5) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5

else if ($#argv == 6) then
  graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6

else if ($#argv == 7) then
  graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6 $mk7 -f $7

else if ($#argv == 8) then
 graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6 $mk7 -f $7 $mk8 -f $8

endif

