#! /bin/csh -f
# rhz281

nice +20

#stim hz281.n

#nc -t -s exponb 4 -s expona 2 hz281x.n >& hz281xa.r  
#nc -t -s conda  0 -s condb  0 hz281x.n >& hz281xb.r  
#
#nc -t -s exponb 8 -s expona 2 hz281.n >& hz281aa.r  
#nc -t -s exponb 4 -s expona 2 hz281.n >& hz281ab.r  
#nc -t -s exponb 2 -s expona 2 hz281.n >& hz281ac.r  
#nc -t -s exponb 1 -s expona 2 hz281.n >& hz281ad.r  
#
#nc -t -s exponb 8 -s expona 4 hz281.n >& hz281ba.r  
#nc -t -s exponb 2 -s expona 4 hz281.n >& hz281bb.r  
#nc -t -s exponb 1 -s expona 4 hz281.n >& hz281bc.r  
#
#nc -t -s exponb 2 -s expona 8   hz281.n >& hz281ca.r  
#nc -t -s exponb 2 -s expona 4   hz281.n >& hz281cb.r  
#nc -t -s exponb 2 -s expona 1   hz281.n >& hz281cd.r  
#
#nc -t -s exponb 4 -s expona 8   hz281.n >& hz281da.r  
#nc -t -s exponb 4 -s expona 4   hz281.n >& hz281db.r  
#nc -t -s exponb 4 -s expona 2   hz281.n >& hz281dc.r  
#nc -t -s exponb 4 -s expona 1   hz281.n >& hz281dd.r  
#
#nc -t -s conda 0    -s condb 1e-9 hz281.n >& hz281ea.r  
#nc -t -s conda 1e-9 -s condb 0    hz281.n >& hz281eb.r  
#nc -t -s conda 0    -s condb 0    hz281.n >& hz281ec.r  
#nc -t -s expona 100 -s exponb 100 hz281.n >& hz281ed.r  
#nc -t -s expona 100 -s exponb 100 -s conda 2e-10 -s condb 2e-10 \
#			hz281.n >& hz281ee.r  
#
#nc -t -s gjcond 200e-9 hz281.n >& hz281fa.r  
#nc -t -s gjcond 100e-9 hz281.n >& hz281fb.r  
#nc -t -s gjcond  40e-9 hz281.n >& hz281fc.r  
#nc -t -s gjcond  20e-9 hz281.n >& hz281fd.r  
#nc -t -s gjcond  0     hz281.n >& hz281fe.r  
#
#nc -t -s hbgjcond 100e-9 hz281.n >& hz281ga.r  
#nc -t -s hbgjcond  40e-9 hz281.n >& hz281gb.r  
#nc -t -s hbgjcond  10e-9 hz281.n >& hz281gc.r  
#nc -t -s hbgjcond  5e-9  hz281.n >& hz281gd.r  
#nc -t -s hbgjcond  2e-9  hz281.n >& hz281ge.r  
#nc -t -s hbgjcond  0     hz281.n >& hz281gf.r  
#
#nc -t -s hagjcond 400e-9 hz281.n >& hz281ha.r  
#nc -t -s hagjcond 200e-9 hz281.n >& hz281hb.r  
#nc -t -s hagjcond 100e-9 hz281.n >& hz281hc.r  
#nc -t -s hagjcond  40e-9 hz281.n >& hz281hd.r  
#nc -t -s hagjcond  20e-9 hz281.n >& hz281he.r  
#nc -t -s hagjcond  0     hz281.n >& hz281hf.r  
#nc -t -s hagjcond  0     -s hbgjcond 0 hz281.n >& hz281hg.r  

#nc -t -s exponf 3 -s expona 2 hz281.n >& hz281ja.r  
#nc -t -s exponf 4 -s expona 2 hz281.n >& hz281jb.r  
#nc -t -s exponf 6 -s expona 2 hz281.n >& hz281jc.r  

#nc -t -s conda 7e-10 -s condb 7e-10 hz281.n >& hz281ma.r  
#nc -t -s conda 5e-10 -s condb 5e-10 hz281.n >& hz281mb.r  
#nc -t -s conda 2e-10 -s condb 2e-10 hz281.n >& hz281mc.r  
#nc -t -s conda 1e-10 -s condb 1e-10 hz281.n >& hz281md.r  

#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 5e-10 hz281.n >& hz281me.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 5e-10 hz281.n >& hz281mf.r  
#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 2e-10 hz281.n >& hz281mg.r  
#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 2e-10 -s exponb 2 \
#                                             hz281.n >& hz281mh.r  
#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 5e-10 -s exponb 2 \
#                                             hz281.n >& hz281mi.r  
#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 1e-10 -s exponb 4 \
#                                             hz281.n >& hz281mj.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 4 \
#                                             hz281.n >& hz281mk.r  
#nc -t -s conda 1e-10 -s condb 1e-10 -s condf 2e-10 -s exponb 2 \
#                                             hz281.n >& hz281ml.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 2 \
#                                             hz281.n >& hz281mm.r  
#
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 5e-10 -s hzthr -.045 \
#                                             hz281.n >& hz281mn.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 2 -s conerm 40000 \
#                                             hz281.n >& hz281mo.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 2 -s conerm 20000 \
#                                             hz281.n >& hz281mp.r  
#nc -t -s conda 2e-10 -s condb 4e-10 -s condf 1e-10 -s exponb 2 \
#                                             hz281.n >& hz281mq.r  
#nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 1.4 \
#                                             hz281.n >& hz281mr.r  
nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 2 -s expona 1.6 \
                                             hz281.n >& hz281ms.r  
nc -t -s conda 2e-10 -s condb 2e-10 -s condf 1e-10 -s exponb 2 -s expona 1.3 \
                                             hz281.n >& hz281mt.r  

#nc -t -s arrsiz 80 -s hbgjcond 200e-9 hz281.n >& hz281da.r  
#nc -t -s arrsiz 80 -s hbgjcond 100e-9 hz281.n >& hz281db.r  
#nc -t -s arrsiz 80 -s hbgjcond  40e-9 hz281.n >& hz281dc.r  
#nc -t -s arrsiz 80 -s hbgjcond  20e-9 hz281.n >& hz281dd.r  
#nc -t -s arrsiz 80 -s hbgjcond  10e-9 hz281.n >& hz281de.r  
#nc -t -s arrsiz 80 -s hbgjcond  5e-9  hz281.n >& hz281df.r  
#nc -t -s arrsiz 80 -s hbgjcond  0     hz281.n >& hz281dg.r  


