#! /bin/csh -f
# rhz280

nice +20

#stim hz280.n

#nc -t -s exponb 8 -s expona 2 hz280.n >& hz280aa.r  
#nc -t -s exponb 4 -s expona 2 hz280.n >& hz280ab.r  
#nc -t -s exponb 2 -s expona 2 hz280.n >& hz280ac.r  
#nc -t -s exponb 1 -s expona 2 hz280.n >& hz280ad.r  
#
#nc -t -s exponb 4 -s expona 4   hz280.n >& hz280ba.r  
#nc -t -s exponb 4 -s expona 2   hz280.n >& hz280bb.r  
#nc -t -s exponb 4 -s expona 1.5 hz280.n >& hz280bc.r  
#nc -t -s exponb 4 -s expona 1   hz280.n >& hz280bd.r  
#
#nc -t -s conda 0    -s condb 1e-9 hz280.n >& hz280ca.r  
#nc -t -s conda 1e-9 -s condb 0    hz280.n >& hz280cb.r  
#nc -t -s conda 0    -s condb 0    hz280.n >& hz280cc.r  
#nc -t -s expona 100 -s exponb 100 hz280.n >& hz280cd.r  
#nc -t -s expona 100 -s exponb 100 -s conda 2e-10 -s condb 2e-10 \
#			hz280.n >& hz280ce.r  
#
#nc -t -s gjcond 200e-9 hz280.n >& hz280da.r  
#nc -t -s gjcond 100e-9 hz280.n >& hz280db.r  
#nc -t -s gjcond  40e-9 hz280.n >& hz280dc.r  
#nc -t -s gjcond  20e-9 hz280.n >& hz280dd.r  
#nc -t -s gjcond  0     hz280.n >& hz280de.r  
#
#nc -t -s hbgjcond 200e-9 hz280.n >& hz280ea.r  
#nc -t -s hbgjcond 100e-9 hz280.n >& hz280eb.r  
#nc -t -s hbgjcond  40e-9 hz280.n >& hz280ec.r  
#nc -t -s hbgjcond  20e-9 hz280.n >& hz280ed.r  
#nc -t -s hbgjcond  10e-9 hz280.n >& hz280ee.r  
#nc -t -s hbgjcond  5e-9  hz280.n >& hz280ef.r  
#nc -t -s hbgjcond  0     hz280.n >& hz280eg.r  
#
#nc -t -s hagjcond 400e-9 hz280.n >& hz280fa.r  
#nc -t -s hagjcond 200e-9 hz280.n >& hz280fb.r  
#nc -t -s hagjcond 100e-9 hz280.n >& hz280fc.r  
#nc -t -s hagjcond  40e-9 hz280.n >& hz280fd.r  
#nc -t -s hagjcond  20e-9 hz280.n >& hz280fe.r  
#nc -t -s hagjcond  0     hz280.n >& hz280ff.r  
#nc -t -s hagjcond  0     -s hbgjcond 0 hz280.n >& hz280fg.r  
#
nc -t -s exponb 8 -s expona 4 hz280.n >& hz280ga.r  
nc -t -s exponb 2 -s expona 4 hz280.n >& hz280gb.r  
nc -t -s exponb 1 -s expona 4 hz280.n >& hz280gc.r  
#
nc -t -s exponb 2 -s expona 4   hz280.n >& hz280ha.r  
nc -t -s exponb 2 -s expona 1.5 hz280.n >& hz280hb.r  
nc -t -s exponb 2 -s expona 1   hz280.n >& hz280hc.r  
#
#
##nc -t -s arrsiz 80 -s hbgjcond 200e-9 hz280.n >& hz280da.r  
##nc -t -s arrsiz 80 -s hbgjcond 100e-9 hz280.n >& hz280db.r  
##nc -t -s arrsiz 80 -s hbgjcond  40e-9 hz280.n >& hz280dc.r  
##nc -t -s arrsiz 80 -s hbgjcond  20e-9 hz280.n >& hz280dd.r  
##nc -t -s arrsiz 80 -s hbgjcond  10e-9 hz280.n >& hz280de.r  
##nc -t -s arrsiz 80 -s hbgjcond  5e-9  hz280.n >& hz280df.r  
##nc -t -s arrsiz 80 -s hbgjcond  0     hz280.n >& hz280dg.r  

