#! /bin/csh -f
# rhz284

nice +20

#stim hz284s.n
#
#nc -t -s exponb 2 -s expona 2 hz284s.n >& hz284s.r  
#nc -t -s exponb 2 -s expona 2 hz284sx.n >& hz284sx.r  
#
#stim hz284bar.n
#
#nc -t -s exponb 2 -s expona 2 hz284bar.n >& hz284bar.r  
#
#stim hz284.n
#
#nc -t -s exponb 2 -s expona 2 hz284x.n >& hz284xa.r  
#nc -t -s conda  0 -s condb  0 hz284x.n >& hz284xb.r  
#
#nc -t -s exponb 8 -s expona 2 hz284.n >& hz284aa.r  
#nc -t -s exponb 4 -s expona 2 hz284.n >& hz284ab.r  
#nc -t -s exponb 2 -s expona 2 hz284.n >& hz284ac.r  
#nc -t -s exponb 1 -s expona 2 hz284.n >& hz284ad.r  
#
#nc -t -s exponb 8 -s expona 4 hz284.n >& hz284ba.r  
#nc -t -s exponb 2 -s expona 4 hz284.n >& hz284bb.r  
#nc -t -s exponb 1 -s expona 4 hz284.n >& hz284bc.r  
#
#nc -t -s exponb 2 -s expona 8   hz284.n >& hz284ca.r  
#nc -t -s exponb 2 -s expona 4   hz284.n >& hz284cb.r  
#nc -t -s exponb 2 -s expona 1   hz284.n >& hz284cd.r  
#
#nc -t -s exponb 4 -s expona 8   hz284.n >& hz284da.r  
#nc -t -s exponb 4 -s expona 4   hz284.n >& hz284db.r  
#nc -t -s exponb 4 -s expona 2   hz284.n >& hz284dc.r  
#nc -t -s exponb 4 -s expona 1   hz284.n >& hz284dd.r  
#
#nc -t -s conda 0     -s condb 2e-10 hz284.n >& hz284ea.r  
#nc -t -s conda 2e-10 -s condb 0     hz284.n >& hz284eb.r  
#nc -t -s conda 0     -s condb 0     hz284.n >& hz284ec.r  
#nc -t -s expona 100  -s exponb 100  hz284.n >& hz284ed.r  
#nc -t -s expona 100  -s exponb 100 -s conda 5e-11 -s condb 5e-11 \
#			hz284.n >& hz284ee.r  
#nc -t -s conda 2e-10 -s condb 0  -s expona 1    hz284.n >& hz284ef.r  
#nc -t -s conda 2e-10 -s condb 0  -s expona 0.5  hz284.n >& hz284eg.r  
#nc -t -s conda 0 -s condb 2e-10  -s exponb 1    hz284.n >& hz284eh.r  
#nc -t -s conda 0 -s condb 2e-10  -s exponb 0.5  hz284.n >& hz284ei.r  
#
#nc -t -s gjcond 200e-9 hz284.n >& hz284fa.r  
#nc -t -s gjcond 100e-9 hz284.n >& hz284fb.r  
#nc -t -s gjcond  40e-9 hz284.n >& hz284fc.r  
#nc -t -s gjcond  20e-9 hz284.n >& hz284fd.r  
#nc -t -s gjcond  0     hz284.n >& hz284fe.r  
#nc -t -s gjcond  10e-9 hz284.n >& hz284ff.r  
#nc -t -s gjcond  40e-9 -s exponb 4 hz284.n >& hz284fg.r  
#
#nc -t -s hbgjcond 200e-9 hz284.n >& hz284ga.r  
#nc -t -s hbgjcond 100e-9 hz284.n >& hz284gb.r  
#nc -t -s hbgjcond  40e-9 hz284.n >& hz284gc.r  
#nc -t -s hbgjcond  10e-9 hz284.n >& hz284gd.r  
#nc -t -s hbgjcond  5e-9  hz284.n >& hz284ge.r  
#nc -t -s hbgjcond  2e-9  hz284.n >& hz284gf.r  
#nc -t -s hbgjcond  0     hz284.n >& hz284gg.r  
#
#nc -t -s hagjcond 400e-9 hz284.n >& hz284ha.r  
#nc -t -s hagjcond 200e-9 hz284.n >& hz284hb.r  
#nc -t -s hagjcond 100e-9 hz284.n >& hz284hc.r  
#nc -t -s hagjcond  40e-9 hz284.n >& hz284hd.r  
#nc -t -s hagjcond  20e-9 hz284.n >& hz284he.r  
#nc -t -s hagjcond  0     hz284.n >& hz284hf.r  
#nc -t -s hagjcond  0     -s hbgjcond 0 hz284.n >& hz284hg.r  
#
#nc -t -s exponf 3 -s expona 2 hz284.n >& hz284ja.r  
#nc -t -s exponf 4 -s expona 2 hz284.n >& hz284jb.r  
#nc -t -s exponf 6 -s expona 2 hz284.n >& hz284jc.r  
#
#nc -t -s exponb 2 -s conerm 40000 hz284.n >& hz284ma.r  
#nc -t -s exponb 2 -s conerm 20000 hz284.n >& hz284mb.r  
#nc -t -s exponb 2 -s conerm 10000 hz284.n >& hz284mc.r  
#
#nc -t -s condf 2e-10     hz284.n >& hz284pa.r  
#nc -t -s condf 2e-10 -s exponb 4    hz284.n >& hz284pb.r
#nc -t -s condf 2e-10 -s exponb 3    hz284.n >& hz284pc.r
#nc -t -s condf 2e-10 -s exponb 2 -s expona 1 hz284.n >& hz284pd.r
#nc -t -s condf 2e-10 -s exponb 3 -s expona 1 hz284.n >& hz284pe.r
#nc -t -s condf 2e-10 -s exponb 3 -s expona .5 hz284.n >& hz284pf.r
#nc -t -s condf 2e-10 -s exponb 2 -s expona .5 hz284.n >& hz284pg.r
#
#nc -t -s gjcond 200e-9 -s conda 0 -s condb 0 hz284.n >& hz284qa.r  
#nc -t -s gjcond 100e-9 -s conda 0 -s condb 0 hz284.n >& hz284qb.r  
#nc -t -s gjcond  40e-9 -s conda 0 -s condb 0 hz284.n >& hz284qc.r  
#nc -t -s gjcond  20e-9 -s conda 0 -s condb 0 hz284.n >& hz284qd.r  
#nc -t -s gjcond  10e-9 -s conda 0 -s condb 0 hz284.n >& hz284qe.r  
#nc -t -s gjcond  0     -s conda 0 -s condb 0 hz284.n >& hz284qf.r  
#
#nc -t -s cstim .2e-10 hz284.n >& hz284ra.r  
#nc -t -s cstim -.2e-10 hz284.n >& hz284rb.r  
#
#stim hz284l.n
#
#nc -t -s arrsiz 80 -s hbgjcond 200e-9 hz284l.n >& hz284na.r  
#nc -t -s arrsiz 80 -s hbgjcond 100e-9 hz284l.n >& hz284nb.r  
#nc -t -s arrsiz 80 -s hbgjcond  40e-9 hz284l.n >& hz284nc.r  
#nc -t -s arrsiz 80 -s hbgjcond  20e-9 hz284l.n >& hz284nd.r  
#nc -t -s arrsiz 80 -s hbgjcond  10e-9 hz284l.n >& hz284ne.r  
#nc -t -s arrsiz 80 -s hbgjcond  5e-9  hz284l.n >& hz284nf.r  
#nc -t -s arrsiz 80 -s hbgjcond  0     hz284l.n >& hz284ng.r  

#nc -t -s arrsiz 80 -s hagjcond 400e-9 hz284l.n >& hz284oa.r  
#nc -t -s arrsiz 80 -s hagjcond 200e-9 hz284l.n >& hz284oa.r  
#nc -t -s arrsiz 80 -s hagjcond 100e-9 hz284l.n >& hz284ob.r  
#nc -t -s arrsiz 80 -s hagjcond  40e-9 hz284l.n >& hz284oc.r  
#nc -t -s arrsiz 80 -s hagjcond  20e-9 hz284l.n >& hz284od.r  
#nc -t -s arrsiz 80 -s hagjcond  10e-9 hz284l.n >& hz284oe.r  
#nc -t -s arrsiz 80 -s hagjcond  5e-9  hz284l.n >& hz284of.r  
#nc -t -s arrsiz 80 -s hagjcond  0     hz284l.n >& hz284og.r  
#nc -t -s arrsiz 80 -s hagjcond  0   -s hbgjcond 0  hz284l.n >& hz284oh.r  

#nc -t -s arrsiz 80 hz284lx.n >& hz284lx.r  

nc -t -s arrsiz 60 hz284pnt.n >& hz284pnt.r  
