#! /bin/csh -f
# rhz281

nice +20

#stim hz282.n

#nc -t -s cstim  0      hz285.n >& hz285aa.r  
#nc -t -s cstim  .2e-10 hz285.n >& hz285ab.r  
#nc -t -s cstim -.2e-10 hz285.n >& hz285ac.r  

nc -t -s spotinten  1e4 hz285s.n >& hz285s.aa.r  
nc -t -s spotinten  1e5 hz285s.n >& hz285s.ab.r  
nc -t -s spotinten  2e5 hz285s.n >& hz285s.ac.r  
nc -t -s spotinten  5e5 hz285s.n >& hz285s.ad.r  
nc -t -s spotinten  1e6 hz285s.n >& hz285s.ae.r  
nc -t -s spotinten  2e6 hz285s.n >& hz285s.af.r  
nc -t -s spotinten  5e6 hz285s.n >& hz285s.ag.r  
nc -t -s spotinten  1e7 hz285s.n >& hz285s.ah.r  
nc -t -s spotinten  2e7 hz285s.n >& hz285s.ai.r  
nc -t -s spotinten  5e7 hz285s.n >& hz285s.aj.r  
nc -t -s spotinten  1e8 hz285s.n >& hz285s.ak.r  
nc -t -s spotinten  1e9 hz285s.n >& hz285s.al.r  

