#! /bin/csh -f
# rhz281

nice +20

#stim hz282.n

#nc -t -s cstim 3e-10 hz282.n >& hz282ab.r  
#nc -t -s cstim 2e-10 hz282.n >& hz282ac.r  
#nc -t -s cstim 1e-10 hz282.n >& hz282ad.r  
#nc -t -s cstim .5e-10 hz282.n >& hz282ae.r  

#nc -t -s cstim .5e-10 -s fbtau 16 hz283.n >& hz283ba.r  
#nc -t -s cstim .5e-10 -s fbtau 16 -s fstau 100 -s expons 4 hz283.n >& hz283bb.r  
#nc -t -s fbtau 16 hz282.n  >& hz282ca.r  
#nc -t -s fbtau 25 hz282.n  >& hz282cb.r  
#nc -t -s fbtau 50 hz282.n  >& hz282cc.r  
#nc -t -s fbtau 100 hz282.n >& hz282cd.r  
#nc -t -s fbtau 200 hz282.n >& hz282ce.r  

#nc -t -s fbtau 16 -s dri 100 hz282.n  >& hz282da.r  
#nc -t -s fbtau 25 -s dri 100 hz282.n  >& hz282db.r  
#
#  current gives feedback transient
#
nc -t -s cstim .5e-10 -s fbtau 16  hz282.n >& hz282ea.r  
#nc -t -s cstim .5e-10 -s fbtau 25  hz282.n >& hz282eb.r  
nc -t -s cstim .5e-10 -s fbtau 50  hz282.n >& hz282ec.r  
nc -t -s cstim .5e-10 -s fbtau 100 hz282.n >& hz282ed.r  
nc -t -s cstim .5e-10 -s fbtau 200 hz282.n >& hz282ee.r  

nc -t -s cstim 1e-10 -s fbtau 16  hz282.n >& hz282fa.r  
nc -t -s cstim 1e-10 -s fbtau 25  hz282.n >& hz282fb.r  
nc -t -s cstim 1e-10 -s fbtau 50  hz282.n >& hz282fc.r  
nc -t -s cstim 1e-10 -s fbtau 100 hz282.n >& hz282fd.r  
nc -t -s cstim 1e-10 -s fbtau 200 hz282.n >& hz282fe.r  


