#! /bin/csh -f
#
#
grc aii.20.p aii.10.p aii.4.p aii.2.p aii.1.p aii.0.p | vid -c \
	| ctomv > aii.3a.psm
#
grc aii.20.px aii.10.px aii.4.px aii.2.px aii.1.px aii.0.px | vid -c \
	| ctomv > aii.3b.psm
#
grc aii.20.pa aii.10.pa aii.4.pa aii.2.pa aii.1.pa aii.0.pa | vid -c \
	| ctomv > aii.3c.psm
#
grc aii.20.pax aii.10.pax aii.4.pax aii.2.pax aii.1.pax aii.0.pax | vid -c \
	| ctomv > aii.3d.psm
#
grc aii.20.p aii.10.p aii.4.p aii.2.p aii.1.p aii.0.p | vid -c \
	| cblue > aii.3a.ps
#
grc aii.20.px aii.10.px aii.4.px aii.2.px aii.1.px aii.0.px | vid -c \
	| cblue > aii.3b.ps
#
grc aii.20.pa aii.10.pa aii.4.pa aii.2.pa aii.1.pa aii.0.pa | vid -c \
	| cblue > aii.3c.ps
#
grc aii.20.pax aii.10.pax aii.4.pax aii.2.pax aii.1.pax aii.0.pax | vid -c \
	| cblue > aii.3d.ps
#
plotmod -f -n -p 1-7 aii4.1.r | vid -c | ctomv > aii4.1a.psm
plotmod -f -n -p 1-2 aii4.1.r | vid -c | ctomv > aii4.1.psm
plotmod -f -n -p 1-2 aii4.2.r | vid -c | ctomv > aii4.2.psm
plotmod -f -n -p 1-2 aii4.3.r | vid -c | ctomv > aii4.3.psm
plotmod -f -n -p 1-7 aii4.3.r | vid -c | ctomv > aii4.3a.psm
plotmod -f -n -p 1-2 aii4.4.r | vid -c | ctomv > aii4.4.psm
plotmod -f -n -p 1-2 aii4.5.r | vid -c | ctomv > aii4.5.psm
plotmod -f -n -p 1-2 aii4.6.r | vid -c | ctomv > aii4.6.psm
plotmod -f -n -p 1-2 aii4.7.r | vid -c | ctomv > aii4.7.psm
#
plotmod -f -n -p 1-7 aii4.1s.r | vid -c | ctomv > aii4.1sa.psm
plotmod -f -n -p 1-7 aii4.2s.r | vid -c | ctomv > aii4.2s.psm
#
plotmod -f -n -p 1-2 aii4.6s.r | vid -c | ctomv > aii4.6s.psm
plotmod -f -n -p 1-2 aii4.7s.r | vid -c | ctomv > aii4.7s.psm
plotmod -f -n -p 1-7 aii4.6s.r | vid -c | ctomv > aii4.6sa.psm
plotmod -f -n -p 1-7 aii4.7s.r | vid -c | ctomv > aii4.7sa.psm
#
plotmod -f -n -p 1-7 aii4.1.1.r  | vid -c | ctomv > aii4.1a.1.psm
#
plotmod -f -n -p 1-2 aii4.4.1.r | vid -c | ctomv > aii4.4.1.psm
#
plotmod -f -n -p 1-2 aii4.10.1.r | vid -c | ctomv > aii4.10.1.psm
plotmod -f -n -p 1-2 aii4.10.2.r | vid -c | ctomv > aii4.10.2.psm

