#! /bin/csh -f
#
#
nice +20

nc -f -n -t                       aii4.n > aii4.1.r
nc -f -n -t -s nona 1             aii4.n > aii4.2.r
nc -f -n -t -s nogj 1             aii4.n > aii4.3.r
nc -f -n -t -s nona 1  -s nogj 1  aii4.n > aii4.4.r
nc -f -n -t -s stim1 1            aii4.n > aii4.5.r
nc -f -n -t -s slowr 0            aii4.n > aii4.6.r
nc -f -n -t -s slowr 0 -s nona 1  aii4.n > aii4.7.r

nc -f -n -t                      -s nfv 0 aii4.n > aii4.1s.r
nc -f -n -t -s nona 1            -s nfv 0 aii4.n > aii4.2s.r
nc -f -n -t -s nogj  1           -s nfv 0 aii4.n > aii4.3s.r
nc -f -n -t -s nona 1  -s nogj 1 -s nfv 0 aii4.n > aii4.4s.r
nc -f -n -t -s stim1 1           -s nfv 0 aii4.n > aii4.5s.r
nc -f -n -t -s slowr 0           -s nfv 0 aii4.n > aii4.6s.r
nc -f -n -t -s slowr 0 -s nona 1  -s nfv 0 aii4.n > aii4.7s.r

nc -s gjcond 1e-10 -f -n -t                       aii4.n > aii4.1.1.r
nc -s gjcond 1e-10 -f -n -t -s nona 1             aii4.n > aii4.1.2.r
nc -s gjcond 1e-10 -f -n -t -s nogj 1             aii4.n > aii4.1.3.r
nc -s gjcond 1e-10 -f -n -t -s nona 1  -s nogj 1  aii4.n > aii4.1.4.r
nc -s gjcond 1e-10 -f -n -t -s stim1 1            aii4.n > aii4.1.5.r
nc -s gjcond 1e-10 -f -n -t -s slowr 0            aii4.n > aii4.1.6.r
nc -s gjcond 1e-10 -f -n -t -s slowr 0 -s nona 1  aii4.n > aii4.1.7.r

nc -s gjcond 4e-10 -f -n -t                       aii4.n > aii4.4.1.r
nc -s gjcond 4e-10 -f -n -t -s nona 1             aii4.n > aii4.4.2.r
nc -s gjcond 4e-10 -f -n -t -s nogj 1             aii4.n > aii4.4.3.r
nc -s gjcond 4e-10 -f -n -t -s nona 1  -s nogj 1  aii4.n > aii4.4.4.r
nc -s gjcond 4e-10 -f -n -t -s stim1 1            aii4.n > aii4.4.5.r
nc -s gjcond 4e-10 -f -n -t -s slowr 0            aii4.n > aii4.4.6.r
nc -s gjcond 4e-10 -f -n -t -s slowr 0 -s nona 1  aii4.n > aii4.4.7.r

nc -s gjcond 1e-9 -f -n -t                       aii4.n > aii4.10.1.r
nc -s gjcond 1e-9 -f -n -t -s nona 1             aii4.n > aii4.10.2.r
nc -s gjcond 1e-9 -f -n -t -s nogj 1             aii4.n > aii4.10.3.r
nc -s gjcond 1e-9 -f -n -t -s nona 1  -s nogj 1  aii4.n > aii4.10.4.r
nc -s gjcond 1e-9 -f -n -t -s stim1 1            aii4.n > aii4.10.5.r
nc -s gjcond 1e-9 -f -n -t -s slowr 0            aii4.n > aii4.10.6.r
nc -s gjcond 1e-9 -f -n -t -s slowr 0 -s nona 1  aii4.n > aii4.10.7.r

column 8 aii4.2.r >  aii4.2n
column 8 aii4.4.r >  aii4.4n
column 8 aii4.4.2.r > aii4.4.2n
column 8 aii4.4.4.r > aii4.4.4n
column 8 aii4.10.2.r > aii4.10.2n
column 8 aii4.10.4.r > aii4.10.4n
