#!/bin/bash

if [ "$RETSIM_CMD" == "" ]; then
    RETSIM_CMD="retsim"
fi
echo "# Running simulations with command '$RETSIM_CMD'"

make

run_retsim_tofiles()
{
	RUNCMD="$RETSIM_CMD --expt $EXPT --expt_desc _$1 --ninfo 3 $ALL_PARAMS -v $NOSKIP > dsgc_$1.r 2>> dsgc_$1.txt &"
	echo $RUNCMD > dsgc_$1.txt
	$RETSIM_CMD --expt $EXPT --expt_desc _$1 --ninfo 3 $ALL_PARAMS -v $NOSKIP > dsgc_$1.r 2>> dsgc_$1.txt &
}

run_retsim_tovid()
{
	RUNCMD="$RETSIM_CMD --expt $EXPT --expt_desc $1 --ninfo 3 $ALL_PARAMS -v $NOSKIP"
	echo $RUNCMD
	`$RUNCMD  | vid $VID_ARGS`
}


run_curinj()
{
	SDUR=1
	STIME=1
	ENDWAIT=.05
	
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp -.2e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_-200
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp -.1e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_-100
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp 0e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_0
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp .1e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_100
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp .2e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_200
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp .3e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_300
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp .4e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_400
	STIM_PARAMS="--stimdur $SDUR --starttime $STIME --endwait $ENDWAIT --stimamp .5e-9 --measure_rin 0"
	ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"
	run_retsim_tofiles calib_500
}


EXPT="dsgc_calib"

VID_ARGS="-w 1.85"
NOSKIP="-y 16 -z 256"

SIM_PARAMS="--ninfo 3 --tempcel 35 --timinc 5e-6 --samprate 100000"

MORPH_PARAMS="--dsgcfile runconf/morph_DS060825 --ath_dia .7 --dend_dia_factor 1 --tempcel 35 --complam 0.03 --dri 200"
#DISP_PARAMS="--make_movie 1 --space_time 1 --show_inputs 0 --show_actual_release 0"
DISP_PARAMS="--make_movie 0 --space_time 0 --show_inputs 0 --show_actual_release 0"
CHAN_PARAMS="--dsgcdensfile runconf/dens_dsgc_DS060825 --vk -0.100 --vna 0.065 --dqh 2.3 --dqm 2.3 --vnoise 0"

DESC="_calib"
STIM_PARAMS="--starttime .005 --stimdur 0.800 --endwait 0 --stimamp 0e-9"

STIM_PARAMS="--stimdur .050 --starttime .050 --endwait 0 --stimamp .300e-9 --measure_rin 0"
ALL_PARAMS="$SIM_PARAMS $MORPH_PARAMS $CHAN_PARAMS $DISP_PARAMS $STIM_PARAMS"

#run_retsim_tofile calib
#run_retsim_tovid calib_-200
run_curinj

