#!/bin/bash


ps2ppm $1_*.ps

cnt=0

#count files
for file in `find ./ -name "$1_*.ps"`
do
    fname=`basename $file`;
    dname=`dirname $file`;
    fullname=$dname/$fname;
    cnt=$(($cnt+1))
    
    #echo "cnt=$cnt, $fullname";
done

#blend together backgrounds using movconvert
movconvert -f $1_ -n $cnt

#join .ppms together into video
ffmpeg -f image2 -i $1_%04d.ppm $1.mpg
