#! /usr/bin/perl
#
#
#  run variable contrast with/without inhibition
#
@morphfilevals = (
	"morph_sbac_168c",
	"morph_sbac_3d",
	"morph_R1MS151208_05-2",
	"morph_R1MS151208_06",
	"morph_R1MS151208_10",
	"morph_R1MS151215_07",
	"morph_R1MS151216_01",
	"morph_R1MS151216_03"
	);

$morphnum = $#morphfilevals + 1;

@synanpovals = (100,200);
$synannum = $#synanpovals + 1;

@drivals = (1,10,50,100,200,400);
$drinum = $#drivals + 1;

@cavals = (1e-3);  # cadist
$canum = $#cavals + 1;

@navals = (3.0e-3);
$nanum = $#navals + 1;

@contvals = (0.0060, 0.0080);
$contnum = $#contvals + 1;

$densfile = "dens_sbac_chans.n";

$sdia = 0;
$spdia = 0;
$sbarr = 0;
# $cadist = 1e-3;
$cadist = 0;
# $nadist = 3e-3;
$nadist = 0;
$stimtype = 6;
$dri = 75;
$sb_rm = 0;
$sb_rmd = 0;
$dcm = 0.8e-6;
$dsomadia = 11;

$predur = 0.05;
$synanpo = 90;

$sbac_thetax = 0;
$sbac_thetay = 0;

$radincr = 20;		# plot location x increment
$soma_z = -50;

$orad1 = 60;
$irad2 = 75;
$orad2 = 150;


$isynanpo = 60; # outer radius for postsynaptic inhibition
# $isynanpo = 150; # outer radius for postsynaptic inhibition


$dbp1_cond = 1.5e-10;
$sb_inhib = $sbac_inhib = 80e-12;
$minten = -0.038;
$vhold = -0.064;

use Getopt::Long;

&GetOptions ("relangle=f" => \$relangle,
             "sdia=f"      => \$sdia,
             "spdia=f"     => \$spdia,
             "minten=i"    => \$minten,
             "sbarr=i"     => \$sbarr,
             "sbspac=f"    => \$sbspac,
             "barlength=f" => \$barlength,
	     "cadist=f"    => \$cadist,
	     "nadist=f"    => \$nadist,
	     "synanpo=f"   => \$synanpo,
	     "isynanpo=f"  => \$isynanpo,
	     "dbp1_cond=f" => \$dbp1_cond,
	     "sb_inhib=f"  => \$sb_inhib,
	     "wac_g=f"     => \$wac_g,
	     "predur=f"    => \$predur,
	     "stimtype=f"  => \$stimtype,
	     "dri=f"       => \$dri,
	     "sb_rm=f"     => \$sb_rm,
	     "sb_rmd=f"    => \$sb_rmd,
	     "drm=f"       => \$drm,
	     "dcm=f"       => \$dcm,
	     "elec_rs=f"   => \$elec_rs,
	     "dsomadia=f"   => \$dsomadia,
	     "morph_file=s"   => \$morph_file
	    );

$sd = sprintf("%4.2f",$sdia);
if ($spdia==0) {$spdia = $sdia;}

if ($sb_rm==0)  {$sb_rm = $drm;}
if ($sb_rmd==0) {$sb_rmd = $sb_rm;}


# for ($f=0; $f<$morphnum; $f++) {
#    $morph_file = $morphfilevals[$f];
#    for ($d=0; $d<$drinum; $d++) {
#        $dri = $drivals[$d];

        $fn = 0;
        for ($f=0; $f<$morphnum; $f++) {
            if ($morph_file eq $morphfilevals[$f]) {$fn = $f + 1;}
        }

        for ($s=0; $s<$synannum; $s++) {
          $synanpo = $synanpovals[$s];
          for ($c=0; $c<$contnum; $c++) {
               $cont = sprintf("%6.4f",$contvals[$c]);

	        if ($fn==1) {		# morph_sbac_168c
		     $soma_z = -50;
		     $sdia = 0.3;
	             $radincr = 20;
		     $sbac_thetax = 4;
		     $sbac_thetay = 3;
		     if ($synanpo==200) { 
			     $orad1 = 57;
			     $irad2 = 100;
			     $orad2 = 119;
		     } else {
			     $orad1 = 51;
			     $irad2 = 81;
			     $orad2 = 150;
		     }
	        }
	        if ($fn==2) {		# morph_sbac3d
		     $soma_z = -42;
		     $sdia = 0.5;
		     $spdia = 0.7;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==3) {		# morph_R1MS151208_05-2
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==4) {		# morph_R1MS151208_06
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==5) {		# morph_R1MS151208_10
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==6) {		# morph_R1MS151215_07
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==7) {		# morph_R1MS151216_01
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	        if ($fn==8) {		# morph_R1MS151216_03
		     $soma_z = -25;
	             $radincr = 12;
		     $sbac_thetax = 0;
		     $sbac_thetay = 0;
		     if ($synanpo==200) { 
			     $orad1 = 60;
			     $irad2 = 80;
			     $orad2 = 150;
		     } else {
		             $synanpo=80;
			     $orad1 = 50;
			     $irad2 = 55;
			     $orad2 = 150;
			     $dbp1_cond = 2.5e-10;
		     }
	        }
	     if ($sdia==0) { $sdia = 0.5; }
	     if ($spdia==0) { $spdia = $sdia; }

             system ("echo $morph_file cont $cont synanpo $synanpo dri $dri drm $drm sdia $sd");
             system ("mosrun -l retsim --runstim6 1 --expt sbac_chans --sbac_file $morph_file  --sbac_densfile $densfile --sb_rm 1e4 --sbarr $sbarr --sb_vs -0.049 --sb_vr -0.060 --radincr $radincr --soma_z $soma_z --sbac_thetax $sbac_thetax --sbac_thetay $sbac_thetay --predur $predur --vhold $vhold --minten $minten --scontrast $cont --dri $dri --sb_rm $sb_rm --elec_rs $elec_rs --ninfo 2 --run_vclamp 1 --dsomadia $dsomadia --sdia $sdia --spdia $spdia --dSomaDia 10 --stimtype $stimtype --prestimdur 0.1 --stimtime 0.05 --spotdur 0.1 --orad1 $orad1 --irad2 $irad2 --orad2 $orad2 --nadist $nadist --namid $nadist --kdist 2e-3 --kmid 2e-3 --kprox 2e-3 --ksoma 3e-3 --cadist $cadist --camid $cadist --plotlabel sbac_stim_2annuli.$morph_file.$cont.$synanpo.$dri.$drm -r 12346 --n_hpb1 0 --dbp1_cond $dbp1_cond --dbp1_nscale -2.1 --sbac_nscale -3.05 --sbaclm 0.1 --no_excit 1 --sbac_synanpo $synanpo --mxrot 0 --Vmin -0.06 --Vmax -0.045 >& sbac_stim_2annuli.$morph_file.$cont.$synanpo.$dri.$drm.r &");
   	 sleep(1);
          }
}


