#!/bin/sh

######################
#Uniform Presentation#
######################
 
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .005 -v retsim1.n > intervaltest_005.r 2> intervaltest_005.output

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .007 -v retsim1.n > intervaltest_007.r 2> intervaltest_007.output


#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .01 -v retsim1.n > intervaltest_010.r 2> intervaltest_010.output


###############
#Random Trials#
###############

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --numtrials 6 --randomtrials 1 --rseed 42582125348133 --recordcbps 1 --sinten .005 -v retsim1.n  > intervaltest_cbpdata_005.r 2> intervaltest_cbpdata_005.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --numtrials 6 --randomtrials 1 --rseed 42582125348133 --recordcbps 1 --sinten .007 -v retsim1.n  > intervaltest_cbpdata_007.r 2> intervaltest_cbpdata_007.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --numtrials 6 --randomtrials 1 --rseed 42582125348133 --recordcbps 1 --sinten .01 -v retsim1.n  > intervaltest_cbpdata_010.r 2> intervaltest_cbpdata_010.txt

############################
#Modifying High Pass Filter#
############################

#no filter 5mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 0 --recordcbps 1 --sinten .005 -v retsim1.n  > intervaltest_005_nohp.r 2> intervaltest_005_nohp.txt
#no filter 10mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 0 --recordcbps 1 --sinten .010 -v retsim1.n  > intervaltest_010_nohp.r 2> intervaltest_010_nohp.txt

#filter 10ms time constant 5mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 1 --hpconst 10 --recordcbps 1 --sinten .005 -v retsim1.n  > intervaltest_005_hpfilt.10.0.7.r 2> intervaltest_005_hpfilt.10.0.7.txt

#filter 10ms time constant 10mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 1 --hpconst 10 --recordcbps 1 --sinten .010 -v retsim1.n  > intervaltest_010_hpfilt.10.0.7.r 2> intervaltest_010_hpfilt.10.0.7.txt

#filter 25ms time constant 5mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 1 --hpconst 25 --recordcbps 1 --sinten .005 -v retsim1.n  > intervaltest_005_hpfilt.25.0.7.r 2> intervaltest_005_hpfilt.25.0.7.txt

#filter 25ms time constant 10mV
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 1 --hpconst 25 --recordcbps 1 --sinten .010 -v retsim1.n  > intervaltest_010_hpfilt.25.0.7.r 2> intervaltest_010_hpfilt.25.0.7.txt


###################
#Smaller Spot Size#
###################
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 50 --s1locx 0 --s1locy 0 --numtrials 6 --hpfilt 0 --recordcbps 1 --sinten .012 -v retsim1.n  > intervaltest_012_nohp_ss.r 2> intervaltest_012_nohp_ss.txt



#######################
#Independent Spot maps#
#######################
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx -80 --s1locy 85 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid1.r 2> rfmap_grid1.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx -20 --s1locy 85 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid2.r 2> rfmap_grid2.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx 40 --s1locy 85 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid3.r 2> rfmap_grid3.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx -80 --s1locy 0 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid5.r 2> rfmap_grid5.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx -20 --s1locy 0 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid6.r 2> rfmap_grid6.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx 40 --s1locy 0 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid7.r 2> rfmap_grid7.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --numtrials 3 --postrecordtime .003 --s1locx 100 --s1locy 0 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_grid8.r 2> rfmap_grid8.txt



##############
#Full RF maps#
##############
#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --rfmap 1 --sequence 0 --postrecordtime .003 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005  --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_full_seq0.r 2> rfmap_full_seq0.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --rfmap 1 --sequence 1 --postrecordtime .003 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005  --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_full_seq1.r 2> rfmap_full_seq1.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --rfmap 1 --sequence 2 --postrecordtime .003 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005  --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_full_seq2.r 2> rfmap_full_seq2.txt

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --rfmap 1 --sequence 3 --postrecordtime .003 --hpfilt 0 --recordcbps 0 --sinten .010 --starttime .005  --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 -v retsim1.n > rfmap_full_seq3.r 2> rfmap_full_seq3.txt

# vid -c -B 0 -P dsgc_cbp_bar_dt_   


nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --stimdur .05 --endwait .005 --sdia 100 --make_movie 0 --space_time 0 --showdsgc 1 -v retsim1.n | vid -S .1 -w 1.85

