#!/bin/sh

NC_CMD="nc"

run_nc() {
  $NC_CMD --expt $EXPT --expt_desc $DESC --ninfo 3 $MISC_VARS $CHAN_VARS $STIM_VARS $RECORD_VARS -v retsim1.n > dsgc_rfmap_$DESC.r 2> dsgc_rfmap_$DESC.txt
}

run_nc_debug() {
  $NC_CMD --expt $EXPT --expt_desc $DESC --ninfo 3 $MISC_VARS $CHAN_VARS $STIM_VARS $RECORD_VARS -v retsim1.n | vid -S .1 -w 1.85
}

rseed1=49573252385
rseed2=36932478098
rseed3=90175289544
rseed4=69884821923

DATA_DIR=/data/retina/data/rfmap/wsoma

#DSGC RF map analysis
EXPT=dsgc_rfmap_analysis
STIM_VARS="--sdia 55"
RECORD_VARS="--normalize 1 --make_movie 0 --space_time 0 --show_inputs 0 --show_actual_release 0 --recordlocs 0"

DESC="avg_25wk_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug


DESC="avg_none_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug

DESC="avg_25_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug

DESC="avg_50_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug&
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug


DESC="avg_75_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
run_nc_debug
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug&

DESC="avg_100_.5"
MISC_VARS="--disptype spike --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug&
MISC_VARS="--disptype vavg --complam 0.05 --dend_dia_factor 1 --datadir $DATA_DIR"
#run_nc_debug&


