#!/bin/sh

NC_CMD="nc"

run_nc() {
  $NC_CMD --expt $EXPT --expt_desc $DESC --ninfo 3 $MISC_VARS $CHAN_VARS $STIM_VARS $RECORD_VARS -v retsim1.n > dsgc_rfmap_$DESC.r 2> dsgc_rfmap_$DESC.txt
}

run_nc_debug() {
  $NC_CMD --expt $EXPT --expt_desc $DESC --ninfo 3 $MISC_VARS $CHAN_VARS $STIM_VARS $RECORD_VARS -v retsim1.n | vid -S .1 -w 1.85
}

rseed1=49573252385
rseed2=36932478098
rseed3=90175289544
rseed4=69884821923

EXPT=dsgc_cbp_rfmap
STIM_VARS="--stimtype spot --stimdur 0.1 --stiminterval 0.1 --sdia 55 --rfmap 1 --randomstims 1 --rseed $rseed1 --sinten 0.010 --starttime 0.005"
RECORD_VARS="--recordspikes 0 --recordvavg 0 --postrecordtime 0.003 --make_movie 0 --space_time 0 --recordregmap 1"
MISC_VARS="--hpfilt 0 --complam 0.05 --dend_dia_factor 0.5 --light_inhib 0"
run_nc_debug


# New Dendritic/Somatic Spike Maps
# Slightly larger stimulus, and longer duration
# Modulation of Na channel densities at soma and dendrites, and dendrite diameter
EXPT=dsgc_cbp_rfmap
STIM_VARS="--stimtype spot --stimdur 0.1 --stiminterval 0.1 --sdia 60 --rfmap 1 --randomstims 1 --rseed $rseed1 --sinten 0.010 --starttime 0.005"
RECORD_VARS="--recordspikes 1 --recordvavg 1 --postrecordtime 0.003 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1"
MISC_VARS="--hpfilt 0 --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1"

#normal dendrite diameter
DESC="rseed1_none_.5"
CHAN_VARS="--dsgc_na_dend 0 --dsgc_kdr_dend 0 --dsgc_ka_dend 0 --dsgc_kih_dend 0 --dsgc_kca1_dend 0 --dsgc_kca2_dend 0"
#run_nc_debug

DESC="rseed1_25_.5"
CHAN_VARS="--dsgc_na_dend 25e-3 --dsgc_kdr_dend 5e-3 --dsgc_ka_dend 2.5e-3 --dsgc_kih_dend .25e-3 --dsgc_kca1_dend .01e-3 --dsgc_kca2_dend .005e-3"
#run_nc

DESC="rseed1_50_.5"
CHAN_VARS="--dsgc_na_dend 50e-3 --dsgc_kdr_dend 10e-3 --dsgc_ka_dend 5e-3 --dsgc_kih_dend .5e-3 --dsgc_kca1_dend .02e-3 --dsgc_kca2_dend .01e-3"
#run_nc

DESC="rseed1_75_.5"
CHAN_VARS="--dsgc_na_dend 75e-3 --dsgc_kdr_dend 15e-3 --dsgc_ka_dend 8.5e-3 --dsgc_kih_dend .75e-3 --dsgc_kca1_dend .03e-3 --dsgc_kca2_dend .015e-3"
#run_nc

DESC="rseed1_100_.5"
CHAN_VARS="--dsgc_na_dend 100e-3 --dsgc_kdr_dend 20e-3 --dsgc_ka_dend 10e-3 --dsgc_kih_dend 1e-3 --dsgc_kca1_dend .04e-3 --dsgc_kca2_dend .01e-3"
#run_nc

DESC="rseed1_75nok_.5"
CHAN_VARS="--dsgc_na_dend 75e-3 --dsgc_kdr_dend 0 --dsgc_ka_dend 0 --dsgc_kih_dend 0 --dsgc_kca1_dend 0 --dsgc_kca2_dend 0"
#run_nc

DESC="rseed1_100nok_.5"
CHAN_VARS="--dsgc_na_dend 100e-3 --dsgc_kdr_dend 0 --dsgc_ka_dend 0 --dsgc_kih_dend 0 --dsgc_kca1_dend 0 --dsgc_kca2_dend 0"
#run_nc



#larger dendrite diameter
MISC_VARS="--hpfilt 0 --complam 0.05 --dend_dia_factor 0.8 --light_inhib 1"
DESC="rseed1_none_1"
CHAN_VARS="--dsgc_na_dend 0 --dsgc_kdr_dend 0 --dsgc_ka_dend 0 --dsgc_kih_dend 0 --dsgc_kca1_dend 0 --dsgc_kca2_dend 0"
#run_nc

DESC="rseed1_25_1"
CHAN_VARS="--dsgc_na_dend 25e-3 --dsgc_kdr_dend 5e-3 --dsgc_ka_dend 2.5e-3 --dsgc_kih_dend .25e-3 --dsgc_kca1_dend .01e-3 --dsgc_kca2_dend .005e-3"
#run_nc

DESC="rseed1_50_1"
CHAN_VARS="--dsgc_na_dend 50e-3 --dsgc_kdr_dend 10e-3 --dsgc_ka_dend 5e-3 --dsgc_kih_dend .5e-3 --dsgc_kca1_dend .02e-3 --dsgc_kca2_dend .01e-3"
#run_nc

DESC="rseed1_75_1"
CHAN_VARS="--dsgc_na_dend 75e-3 --dsgc_kdr_dend 15e-3 --dsgc_ka_dend 8.5e-3 --dsgc_kih_dend .75e-3 --dsgc_kca1_dend .03e-3 --dsgc_kca2_dend .015e-3"
#run_nc

DESC="rseed1_100_1"
CHAN_VARS="--dsgc_na_dend 100e-3 --dsgc_kdr_dend 20e-3 --dsgc_ka_dend 10e-3 --dsgc_kih_dend 1e-3 --dsgc_kca1_dend .04e-3 --dsgc_kca2_dend .01e-3"
#run_nc


