#!/bin/sh


nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 0 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .005 -v retsim1.n > cbpmap.005.txt 2> cbpmap.005.txt
# | vid -w 1.75
# > intervaltest_005.r 2> intervaltest_005.output

#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .007 -v retsim1.n > intervaltest_007.r 2> intervaltest_007.output


#nc --expt dsgc_cbp_rfmap --complam 0.05 --dend_dia_factor 0.5 --light_inhib 1 --stimdur .1 --ninfo 2 --make_movie 1 --space_time 1 --show_inputs 1 --show_actual_release 1 --stimdur .04 --endwait .01 --sdia 100 --s1locx 0 --s1locy 0 --numtrials 6  --sinten .01 -v retsim1.n > intervaltest_010.r 2> intervaltest_010.output


# | vid -w 1.75
#  > rfmap_010.r 2> rfmap_010.output


#  | vid -w 1.75
#


# vid -c -B 0 -P dsgc_cbp_bar_dt_   
