#! /bin/csh -f
#  grc
#
set pen = 1

#set axis =
#set axis = "-T 3"
set axis = "-T 1"

# set mk =
set mk1 = "-c o"
set mk2 = "-c o"
set mk3 = "-c o"
set mk4 = "-c o"
set mk5 = "-c o"
set mk6 = "-c o"
set mk7 = "-c o"
set mk8 = "-c o"

#set csiz = 
set csiz = "-w 4 -W 4 -v 2"

set min =
#set min = "-m -.1"

#set grid = "-g 0"

set max =
#set max = "-M 1.2"

#set plot = "vid  -m 1.5  -y 6700"

if ($#argv == 1) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 

else if ($#argv == 2) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 

else if ($#argv == 3) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 

else if ($#argv == 4) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4

else if ($#argv == 5) then
   graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5

else if ($#argv == 6) then
  graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6

else if ($#argv == 7) then
  graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6 $mk7 -f $7

else if ($#argv == 8) then
 graph -p $pen $csiz $axis $min $max $mk1 -f $1 $mk2 -f $2 $mk3 -f $3 $mk4 -f $4 $mk5 -f $5 $mk6 -f $6 $mk7 -f $7 $mk8 -f $8

endif

