#! /bin/csh -f
#

nice +20

nc -s crit 1e-6 -s complam .2 -s timinc 1e-6  rpack1i > rpack1i.aa
nc -s crit 1e-6 -s complam .2 -s timinc 2e-6  rpack1i > rpack1i.ab
nc -s crit 1e-6 -s complam .2 -s timinc 5e-6  rpack1i > rpack1i.ac
nc -s crit 1e-6 -s complam .2 -s timinc 1e-5  rpack1i > rpack1i.ad
nc -s crit 1e-6 -s complam .2 -s timinc 2e-5  rpack1i > rpack1i.ae
nc -s crit 1e-6 -s complam .2 -s timinc 5e-5  rpack1i > rpack1i.af
nc -s crit 1e-6 -s complam .2 -s timinc 10e-5 rpack1i > rpack1i.ag
nc -s crit 1e-6 -s complam .2 -s timinc 20e-5 rpack1i > rpack1i.ah
nc -s crit 1e-6 -s complam .2 -s timinc 50e-5 rpack1i > rpack1i.ai
nc -s crit 1e-6 -s complam .2 -s timinc 1e-3  rpack1i > rpack1i.aj

nc -s crit 1e-6 -s complam .1 -s timinc 1e-6  rpack1i > rpack1i.ba
nc -s crit 1e-6 -s complam .1 -s timinc 2e-6  rpack1i > rpack1i.bb
nc -s crit 1e-6 -s complam .1 -s timinc 5e-6  rpack1i > rpack1i.bc
nc -s crit 1e-6 -s complam .1 -s timinc 1e-5  rpack1i > rpack1i.bd
nc -s crit 1e-6 -s complam .1 -s timinc 2e-5  rpack1i > rpack1i.be
nc -s crit 1e-6 -s complam .1 -s timinc 5e-5  rpack1i > rpack1i.bf
nc -s crit 1e-6 -s complam .1 -s timinc 1e-4  rpack1i > rpack1i.bg
nc -s crit 1e-6 -s complam .1 -s timinc 2e-4  rpack1i > rpack1i.bh
nc -s crit 1e-6 -s complam .1 -s timinc 5e-4  rpack1i > rpack1i.bi
nc -s crit 1e-6 -s complam .1 -s timinc 1e-3  rpack1i > rpack1i.bj

#nc -s crit 1e-8 -s complam .05 -s timinc 1e-6  rpack1i > rpack1i.ca
#nc -s crit 1e-8 -s complam .05 -s timinc 2e-6  rpack1i > rpack1i.cb
nc -s crit 1e-8 -s complam .05 -s timinc 5e-6  rpack1i > rpack1i.cc
nc -s crit 1e-8 -s complam .05 -s timinc 1e-5  rpack1i > rpack1i.cd
nc -s crit 1e-8 -s complam .05 -s timinc 2e-5  rpack1i > rpack1i.ce
nc -s crit 1e-8 -s complam .05 -s timinc 5e-5  rpack1i > rpack1i.cf
nc -s crit 1e-8 -s complam .05 -s timinc 10e-5 rpack1i > rpack1i.cg

#nc -s complam .02 -s timinc 1e-6  rpack1i > rpack1i.da
#nc -s complam .02 -s timinc 2e-6  rpack1i > rpack1i.db
nc -s complam .02 -s timinc 5e-6  rpack1i > rpack1i.dc
nc -s complam .02 -s timinc 1e-5  rpack1i > rpack1i.dd
nc -s complam .02 -s timinc 2e-5  rpack1i > rpack1i.de
nc -s complam .02 -s timinc 5e-5  rpack1i > rpack1i.df
nc -s complam .02 -s timinc 10e-5 rpack1i > rpack1i.dg

#nc -s complam .01 -s timinc 1e-6  rpack1i > rpack1i.ea
#nc -s complam .01 -s timinc 2e-6  rpack1i > rpack1i.eb
nc -s complam .01 -s timinc 5e-6  rpack1i > rpack1i.ec
nc -s complam .01 -s timinc 1e-5  rpack1i > rpack1i.ed
nc -s complam .01 -s timinc 2e-5  rpack1i > rpack1i.ee
#nc -s complam .01 -s timinc 5e-5  rpack1i > rpack1i.ef
#nc -s complam .01 -s timinc 10e-5 rpack1i > rpack1i.eg

#nc -s complam .005 -s timinc 1e-6  rpack1i > rpack1i.fa
#nc -s complam .005 -s timinc 2e-6  rpack1i > rpack1i.fb
#nc -s complam .005 -s timinc 5e-6  rpack1i > rpack1i.fc
#nc -s complam .005 -s timinc 1e-5  rpack1i > rpack1i.fd
#nc -s complam .005 -s timinc 2e-5  rpack1i > rpack1i.fe
#nc -s complam .005 -s timinc 5e-5  rpack1i > rpack1i.ff
#nc -s complam .005 -s timinc 10e-5 rpack1i > rpack1i.fg

#nc -s complam .002 -s timinc 1e-6  rpack1i > rpack1i.ga
#nc -s complam .002 -s timinc 2e-6  rpack1i > rpack1i.gb
#nc -s complam .002 -s timinc 5e-6  rpack1i > rpack1i.gc
#nc -s complam .002 -s timinc 1e-5  rpack1i > rpack1i.gd
#nc -s complam .002 -s timinc 2e-5  rpack1i > rpack1i.ge
#nc -s complam .002 -s timinc 5e-5  rpack1i > rpack1i.gf
#nc -s complam .002 -s timinc 10e-5 rpack1i > rpack1i.gg

#nc -s complam .001 -s timinc 1e-6  rpack1i > rpack1i.ha
#nc -s complam .001 -s timinc 2e-6  rpack1i > rpack1i.hb
#nc -s complam .001 -s timinc 5e-6  rpack1i > rpack1i.hc
#nc -s complam .001 -s timinc 1e-5  rpack1i > rpack1i.hd
#nc -s complam .001 -s timinc 2e-5  rpack1i > rpack1i.he
#nc -s complam .001 -s timinc 5e-5  rpack1i > rpack1i.hf
#nc -s complam .001 -s timinc 10e-5 rpack1i > rpack1i.hg

