#! /bin/csh -f
#

nice +20

#nc -s euler 1 -s complam .2 -s timinc 1e-6  rpack1 > rpack1e.aa
#nc -s euler 1 -s complam .2 -s timinc 2e-6  rpack1 > rpack1e.ab
#nc -s euler 1 -s complam .2 -s timinc 5e-6  rpack1 > rpack1e.ac
#nc -s euler 1 -s complam .2 -s timinc 1e-5  rpack1 > rpack1e.ad
#nc -s euler 1 -s complam .2 -s timinc 2e-5  rpack1 > rpack1e.ae
#nc -s euler 1 -s complam .2 -s timinc 5e-5  rpack1 > rpack1e.af
nc -s euler 1 -s complam .2 -s timinc 10e-5 rpack1 > rpack1e.ag
nc -s euler 1 -s complam .2 -s timinc 20e-5 rpack1 > rpack1e.ah
nc -s euler 1 -s complam .2 -s timinc 50e-5 rpack1 > rpack1e.ai
nc -s euler 1 -s complam .2 -s timinc 1e-3  rpack1 > rpack1e.aj

#nc -s euler 1 -s complam .1 -s timinc 1e-6  rpack1 > rpack1e.ba
#nc -s euler 1 -s complam .1 -s timinc 2e-6  rpack1 > rpack1e.bb
#nc -s euler 1 -s complam .1 -s timinc 5e-6  rpack1 > rpack1e.bc
#nc -s euler 1 -s complam .1 -s timinc 1e-5  rpack1 > rpack1e.bd
#nc -s euler 1 -s complam .1 -s timinc 2e-5  rpack1 > rpack1e.be
#nc -s euler 1 -s complam .1 -s timinc 5e-5  rpack1 > rpack1e.bf
nc -s euler 1 -s complam .1 -s timinc 1e-4  rpack1 > rpack1e.bg
nc -s euler 1 -s complam .1 -s timinc 2e-4  rpack1 > rpack1e.bh
nc -s euler 1 -s complam .1 -s timinc 5e-4  rpack1 > rpack1e.bi
nc -s euler 1 -s complam .1 -s timinc 1e-3  rpack1 > rpack1e.bj

#nc -s euler 1 -s complam .05 -s timinc 1e-6  rpack1 > rpack1e.ca
#nc -s euler 1 -s complam .05 -s timinc 2e-6  rpack1 > rpack1e.cb
#nc -s euler 1 -s complam .05 -s timinc 5e-6  rpack1 > rpack1e.cc
#nc -s euler 1 -s complam .05 -s timinc 1e-5  rpack1 > rpack1e.cd
#nc -s euler 1 -s complam .05 -s timinc 2e-5  rpack1 > rpack1e.ce
#nc -s euler 1 -s complam .05 -s timinc 5e-5  rpack1 > rpack1e.cf
#nc -s euler 1 -s complam .05 -s timinc 10e-5 rpack1 > rpack1e.cg

#nc -s euler 1 -s complam .02 -s timinc 1e-6  rpack1 > rpack1e.da
#nc -s euler 1 -s complam .02 -s timinc 2e-6  rpack1 > rpack1e.db
#nc -s euler 1 -s complam .02 -s timinc 5e-6  rpack1 > rpack1e.dc
#nc -s euler 1 -s complam .02 -s timinc 1e-5  rpack1 > rpack1e.dd
#nc -s euler 1 -s complam .02 -s timinc 2e-5  rpack1 > rpack1e.de
#nc -s euler 1 -s complam .02 -s timinc 5e-5  rpack1 > rpack1e.df
#nc -s euler 1 -s complam .02 -s timinc 10e-5 rpack1 > rpack1e.dg

#nc -s euler 1 -s complam .01 -s timinc 1e-6  rpack1 > rpack1e.ea
#nc -s euler 1 -s complam .01 -s timinc 2e-6  rpack1 > rpack1e.eb
#nc -s euler 1 -s complam .01 -s timinc 5e-6  rpack1 > rpack1e.ec
#nc -s euler 1 -s complam .01 -s timinc 1e-5  rpack1 > rpack1e.ed
#nc -s euler 1 -s complam .01 -s timinc 2e-5  rpack1 > rpack1e.ee
#nc -s euler 1 -s complam .01 -s timinc 5e-5  rpack1 > rpack1e.ef
#nc -s euler 1 -s complam .01 -s timinc 10e-5 rpack1 > rpack1e.eg

#nc -s euler 1 -s complam .005 -s timinc 1e-6  rpack1 > rpack1e.fa
#nc -s euler 1 -s complam .005 -s timinc 2e-6  rpack1 > rpack1e.fb
#nc -s euler 1 -s complam .005 -s timinc 5e-6  rpack1 > rpack1e.fc
#nc -s euler 1 -s complam .005 -s timinc 1e-5  rpack1 > rpack1e.fd
#nc -s euler 1 -s complam .005 -s timinc 2e-5  rpack1 > rpack1e.fe
#nc -s euler 1 -s complam .005 -s timinc 5e-5  rpack1 > rpack1e.ff
#nc -s euler 1 -s complam .005 -s timinc 10e-5 rpack1 > rpack1.fg

#nc -s euler 1 -s complam .002 -s timinc 1e-6  rpack1 > rpack1e.ga
#nc -s euler 1 -s complam .002 -s timinc 2e-6  rpack1 > rpack1e.gb
#nc -s euler 1 -s complam .002 -s timinc 5e-6  rpack1 > rpack1e.gc
#nc -s euler 1 -s complam .002 -s timinc 1e-5  rpack1 > rpack1e.gd
#nc -s euler 1 -s complam .002 -s timinc 2e-5  rpack1 > rpack1e.ge
#nc -s euler 1 -s complam .002 -s timinc 5e-5  rpack1 > rpack1e.gf
#nc -s euler 1 -s complam .002 -s timinc 10e-5 rpack1 > rpack1e.gg

#nc -s euler 1 -s complam .001 -s timinc 1e-6  rpack1 > rpack1e.ha
#nc -s euler 1 -s complam .001 -s timinc 2e-6  rpack1 > rpack1e.hb
#nc -s euler 1 -s complam .001 -s timinc 5e-6  rpack1 > rpack1e.hc
#nc -s euler 1 -s complam .001 -s timinc 1e-5  rpack1 > rpack1e.hd
#nc -s euler 1 -s complam .001 -s timinc 2e-5  rpack1 > rpack1e.he
#nc -s euler 1 -s complam .001 -s timinc 5e-5  rpack1 > rpack1e.hf
#nc -s euler 1 -s complam .001 -s timinc 10e-5 rpack1 > rpack1e.hg

