#! /bin/ash
#
# setpppmodem 
#  
# Set default settings for ppp-modem when used by xfm
#
#  Default settings are kept in .xfm/Apps (the "getmail" line).

if [ $# -lt 5 ] 
then
  echo Usage: setpppmodem user remote-machine password
  exit
fi

pppdir=$HOME/.ppp

if [ ! -d $pppdir ] 
then
   mkdir $pppdir
   chmod 700 $pppdir
fi

pppfil=$pppdir/ppp-modem

echo $1 > $pppfil.port
echo $2 > $pppfil.number
echo $3 > $pppfil.ipaddr
echo $4 > $pppfil.user
echo $5 > $pppfil.passwd
chmod 600 $pppfil.port $pppfil.number $pppfil.user $pppfil.passwd $pppfil.ipaddr

xfmdir=$HOME/.xfm
setfile=$xfmdir/Modem

if [ ! -d $xfmdir ] 
then
   echo "setpppmodem: $xfmdir does not exist.  Please run xfm.install". >/dev/console
fi

# first, find the line to be changed
#
awk '!/setpppmodem/{print}
      /setpppmodem/{ start=index($0,"setpppmodem"); 
 line1=substr($0,0,start-1);
 line2="setpppmodem %port--"arg1"% %number--"arg2"% %IP address--"arg3"% %login--"arg4"% %password--xxxxxx%; RELOAD";
      print line1""line2; }
      ' arg1=$1 arg2=$2 arg3=$3 arg4=$4 arg5=$5 $setfile > $setfile.tmp && mv $setfile.tmp $setfile

