#!/bin/bash
#
# makebar
#
# make bar graph by doubling values
#
awk 'BEGIN  {first=1}
     !/^#/  {x = $1; y = $2}
     !/^#/  {if (first) {first=0; yold = y}}
     !/^#/ {print x, yold; print x,y; xold = x; yold = y;}' $1
