#! /bin/bash
#
# split .r files into separate traces
# 
#  db4split --plotn 5  (to use subtracted current)
#  db4split --plotn 6  (to use raw current)
#
for i in $@; do
    echo ${i%.*}.data
    db4split --plotn 6 --info 0 < ${i%.*}.r  > ${i%.*}.data
done

##! /bin/tcsh -f
##
#foreach i ($argv) 
#  echo $i:r.data
#  db4split --plotn 6 --info 0 < $i:r.r  > $i:r.data
#end
