#! /usr/bin/perl
#
#  printdsi_na_files 
#

@sdiavals = (0.26, 0.3, 0.5);
$sdianum = $#sdiavals + 1;

@contvals = (0.002,0.0025,0.003,0.0035,0.0040,0.0045,0.005);
$contnum = $#contvals + 1;

# @sbspacvals = (135,155);         # cell spacing
@sbspacvals = (135);               # cell spacing
$sbspacnum = $#sbspacvals + 1;

# @barvals = (70,300);             # bar length
@barvals = (70);                   # bar length
$barnum = $#barvals + 1;

# @synanvals = (90,100,110);       # synanpo
@synanvals = (110);                # synanpo
$synannum = $#synanvals + 1;

@velvals = (100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000);
$velnum = $#velvals + 1;

@inhvals = (1);
$inhnum = $#inhvals + 1;

@navals = (0.000,0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.010);
$nanum = $#navals + 1;


 $relangle = 300;
     $sdia = 0.22;
    $noinh = 1;
    $sbarr = 107;
   $sbspac = 135;
$barlength = 70;
   $cadist = 2.2e-3;
  $synanpo = 100;
$dbp1_cond = 2.3e-10;


use Getopt::Long;

&GetOptions ("relangle=f" => \$relangle,
             "sdia=f"      => \$sdia,
             "noinh=i"     => \$noinh,
             "sbarr=i"     => \$sbarr,
             "sbspac=f"    => \$sbspac,
             "barlength=f" => \$barlength,
             "cadist=f"    => \$cadist,
             "synanpo=f"   => \$synanpo,
             "dbp1_cond=f" => \$dbp1_cond,
             "sb_inhib=f"  => \$sb_inhib
            );

 $sd = sprintf("%4.2f",$sdia);

for ($d=0; $d<$sdianum; $d++) {
     $sdia = sprintf("%4.2f",$sdiavals[$d]);
      for ($a=0; $a<$synannum; $a++) {
           $synanpo = sprintf("%.3d",$synanvals[$a]);
            for ($c=0; $c<$contnum; $c++) {
	         $cont = sprintf("%6.4f",$contvals[$c]);
                  system ("rm -f sbac_dsi_na.$relangle.$cont.$sdia.txt");

                  for ($n=0; $n<$nanum; $n++) {
                       $nadist = sprintf("%5.3f",$navals[$n]);

#                for ($v=0; $v<$velnum; $v++) {
#	            $vel = sprintf("%.5d",$velvals[$v]);
#                    for ($i=0; $i<$inhnum; $i++) {
#                        $noinh = $inhvals[$i];

system ("echo contrast $cont noinh $noinh nadist $nadist sdia $sdia");
system ("printdsi_na sbac1_midbp_ca.$relangle.$cont.$noinh.$nadist.$sdia.r >> sbac_dsi_na.$relangle.$cont.$sdia.txt");

                 }
           }
      }
}

