#! /usr/bin/perl
#
#  printdsi_soma_files 
#

@cavals = (2.0e-3,2.2e-3, 2.4e-3, 2.6e-3);  # cadist
$canum = $#cavals + 1;

@navals = (0e-3,0.5e-3,1e-3,1.5e-3,2e-3); # na_dist
$nanum = $#navals + 1;



 $relangle = 360;
     $sdia = 0.3;
    $noinh = 0;
    $sbarr = 0;
   $sbspac = 155;
 $stimtype = 2;
$barlength = 70;
   $cadist = 2.2e-3;
  $synanpo = 90;
$dbp1_cond = 2.3e-10;
    $wac_g = 0;
      $nsb = 1;

use Getopt::Long;

&GetOptions ("relangle=f" => \$relangle,
             "sdia=f"      => \$sdia,
             "noinh=i"     => \$noinh,
             "sbarr=i"     => \$sbarr,
             "sbspac=f"    => \$sbspac,
             "barlength=f" => \$barlength,
             "cadist=f"    => \$cadist,
             "synanpo=f"   => \$synanpo,
             "dbp1_cond=f" => \$dbp1_cond,
             "sb_inhib=f"  => \$sb_inhib
            );

$sd = sprintf("%4.2f",$sdia);
$wacg = sprintf("%3.1f",$wac_g*1e10);
$sd = sprintf("%4.2f",$sdia);

   for ($n=0; $n<$nanum; $n++) {
        $nadist = $navals[$n];
        $namid  = $navals[$n];
        $nad    = sprintf("%3.1f",$nadist*1e3);
        for ($b=0; $b<$canum; $b++) {
             $cadist = $cavals[$b];
             $cad    = sprintf("%3.1f",$cadist*1e3);

system ("echo cadist $cadist nadist $nadist sdia $sdia");
system ("printdsi_soma sbac$nsb.midbp_ca.$relangle.0.*.$noinh.$sbspac.$stimtype.$cad.$nad.$sd.$wacg.r > sbac_dsi_soma.$sbspac.$cad.$nad.$sd.txt");
        }
  }

