#!/bin/sh
#
# printpeak
#
# $1=time, V=$30 (col 29 after time), Ca=$31 trace to find max
#
# for sbac1 series only
#
awk "BEGIN {

      Vs  = 16;
      Vt  = 22;
      peakvs1=peakvs2= -0.2;
      peakvt1=peakvt2= -0.2;
      tpeakvs1=tpeakvs2=0;
      tpeakvt1=tpeakvt2=0;
      peak0Time=0.01;
      peak2Time=0.20;
      printf (\"%s: \",\"$1\");
     }
     
     "'/^#/   { if ($1 == "#e") {
		 endexp = $5;
	        peak2Time = endexp / 2;
	      }
	    }
     $1==0.005 { peakvs0 = $Vs; peakvt0 = $Vt; }
     !/^#/ { 
	    if ($1<peak2Time) {
	        if (peakvs1 < $Vs)  { peakvs1 = $Vs; tpeakvs1 = $1; }
	        if (peakvt1 < $Vt)  { peakvt1 = $Vt; tpeakvt1 = $1; }
	    }
	    else {
	        if (peakvs2 < $Vs)  { peakvs2 = $Vs;  tpeakvs2 = $1; }
	        if (peakvt2 < $Vt)  { peakvt2 = $Vt;  tpeakvt2 = $1; }
	    }
	  } 
	END {
	 # printf ("\n"); 
	 # printf ("Peakvs0:  %-6.4g: %-9.4g  \n", peak0Time, peakvs0); 
	 # printf ("Peakvs1:  %-6.4g: %-9.4g  \n", tpeakvs1,  peakvs1); 
	 # printf ("Peakvs2:  %-6.4g: %-9.4g  \n", tpeakvs2,  peakvs2); 
	 # printf ("Peakvt0:  %-6.4g: %-9.4g  \n", peak0Time, peakvt0); 
	 # printf ("Peakvt1:  %-6.4g: %-9.4g  \n", tpeakvt1,  peakvt1); 
	 # printf ("Peakvt2:  %-6.4g: %-9.4g  \n", tpeakvt2,  peakvt2); 
	 peakvsh1 = peakvs0 - peakvs1;
	 peakvsh2 = peakvs0 - peakvs2;
	 peakvth1 = peakvt1 - peakvt0;
	 peakvth2 = peakvt2 - peakvt0;
	 # printf ("Peakvth1:  %-6.4g: %-9.4g  \n", tpeakvt1,  peakvth1); 
	 # printf ("Peakvth2:  %-6.4g: %-9.4g  \n", tpeakvt2,  peakvth2); 
	 printf ("DSI(Vsoma)  %-9.4g   DSI(Vtip) %-9.4g\n", (peakvsh1-peakvsh2)/(peakvsh1+peakvsh2), (peakvth1-peakvth2)/(peakvth1+peakvth2)); 
	}
   ' $1
