#! /usr/bin/perl
#
#
#  run variable contrast with/without inhibition
#
@inhvals = (0, 1);
$inhnum = $#inhvals + 1;
# $ristart = 200;
# $ristop  = 800;
# $ristep  = 100;

$cont = 0.0075;

@contvals = (0.0050, 0.0060, 0.0070, 0.0080);
$contnum = $#contvals + 1;

@velvals = (100, 200, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000);
$velnum = $#velvals + 1;
# $nastart = 600;
# $nastop  = 2000;
# $nastep  = 100;

$sbarr = 107;
$sbspac = 135;
$sdia = 0.22;
$relangle = 300;
$cadist = 2.2e-3;
$barlength = 70;
$synanpo = 100;

# $dbp1_cond = 3e-10;
$dbp1_cond = 2.3e-10;
$sb_inhib = 80e-12;

use Getopt::Long;

&GetOptions ("relangle=f" => \$relangle,
             "sdia=f"      => \$sdia,
             "noinh=i"     => \$noinh,
             "sbarr=i"     => \$sbarr,
             "sbspac=f"    => \$sbspac,
             "barlength=f" => \$barlength,
             "cadist=f"    => \$cadist,
             "synanpo=f"   => \$synanpo,
             "dbp1_cond=f" => \$dbp1_cond,
             "sb_inhib=f"  => \$sb_inhib
            );


$barleng =  sprintf("%.3d",$barlength);
$synanpov = sprintf("%.3d",$synanpo);
$sd = sprintf("%4.2f",$sdia);

for ($i=0; $i<$inhnum; $i++) {
     $noinh = $inhvals[$i];
     for ($c=0; $c<$contnum; $c++) {
         $cont = sprintf("%6.4f",$contvals[$c]);
         for ($v=0; $v<$velnum; $v++) {
             # $vel = $velvals[$v];
             $vel = sprintf("%.5d",$velvals[$v]);
	     system ("echo contrast $cont inh $noinh barlength $barleng synanpo $synanpov sdia $sdia vel $vel");
             system ("mv sbac7_midbp_ca.$relangle.$cont.$noinh.$sbspac.$barleng.$synanpo.$sdia.$vel.r sbac7_midbp_ca.$relangle.$cont.$noinh.$sbspac.$barleng.$synanpov.$sd.$vel.r &");
        }
    }
}


