#!/bin/sh
#
# sbac_dsi_print_c
#
#
awk '
     !/^#/ {
             # print substr($1,35,1);
             if (substr($1,35,1) == "0")
	      print substr($1,20, 6), $5;
             else
              print $5; 
           }
   ' $1
