#!/bin/sh
#
# sbac_dsi_print_v
#
#
awk '
     !/^#/ {
             # print substr($1,31,1);
             if (substr($1,31,1) == "0")
	      print substr($1,20, 6), $3;
             else
              print $3; 
           }
   ' $1
