#!/bin/sh
#
# sbac_dsi_na_print_v
#
#
awk '
     !/^#/ {
             # print substr($1,27,1);
             if (substr($1,27,1) != "0") {
	       line0 = sprintf("%s %6.5f %6.5f", substr($1,29, 5), $3, $5);
               print line0; 
	     }
           }
   ' $1
