#!/bin/sh
#
# sbac_dsi_vel_print_v
#
#
awk '
     !/^#/ {
             # print substr($1,27,1);
             if (substr($1,27,1) == "0")
              line0 = sprintf("%s %6.5f", substr($1, 46, 6), $3);
             else
              print line0,$3; 
           }
   ' $1
